repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.42.1
    hooks:
    - id: commitizen
      stage: commit-msg

  - repo: local
    hooks:
      - id: pytest
        name: Run pytest
        stage: push
        language: system
        pass_filenames: false
        types: [ python ]
        entry: poetry run pytest

      - id: pyright
        name: Run pyright
        stage: push
        language: system
        pass_filenames: false
        types: [ python ]
        entry: poetry run pyright

      - id: ruff
        name: Run ruff
        stage: push
        language: system
        pass_filenames: false
        types: [ python ]
        entry: poetry run ruff check .
