[tool.poetry]
name = "mac_cleanup"
version = "2.2.4"
description = "Python cleanup script for macOS"
authors = ["Drugsosos"]
license = "Apache-2.0 license"
readme = "README.md"
homepage = "https://github.com/mac-cleanup/mac-cleanup-py"
repository = "https://github.com/mac-cleanup/mac-cleanup-py"

classifiers = [ "Environment :: Console", "Operating System :: MacOS", ]

[tool.poetry.urls]
"Documentation" = "https://github.com/mac-cleanup/mac-cleanup-py#install-automatically"
"Issue Tracker" = "https://github.com/mac-cleanup/mac-cleanup-py/issues"


[tool.poetry.dependencies]
python = ">=3.7,<3.12"
rich = "^12.2.0"
toml = "^0.10.2"
inquirer = "^2.10.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
tox = "^3.25.1"
flake8 = "^5.0.4"
mypy = "^0.971"
pytest-cov = "^3.0.0"
types-toml = "^0.10.8"

[tool.poetry.scripts]
mac-cleanup = "mac_cleanup:main"

[options.package_data]
mac_cleanup = "py.typed"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
