name: Tests

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    # The branches below must be a subset of the branches above
    branches:
      - main
      - develop

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11' ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python V${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install tox-gh-actions
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Tests with Tox
        run: tox
