name: Tests

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    # The branches below must be a subset of the branches above
    branches:
      - main
      - develop

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11' ]

    steps:
      - uses: actions/checkout@v3.4.0
      - name: Set up Python V${{ matrix.python-version }}
        uses: actions/setup-python@v4.5.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox-gh-actions
        run: |
          python -m pip install --upgrade pip
          pip install tox-gh-actions
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.3.0
      - name: Install dependencies
        run: poetry install --no-root -v
      - name: Tests with Tox
        run: poetry run tox
